### ISSUE TITLE
Creating two different plots in same cell doesn't work

### ISSUE THREAD

**Issue by bfirsh** [replicate/keepsake#205]
<img width="759" alt="Screen Shot 2020-10-21 at 10 16 15" src="https://user-images.githubusercontent.com/40906/96754728-8f8f2300-1386-11eb-9742-b5019265c1ec.png">

Maybe it should start a new plot if the axes are different.

**Comment by enochkan** [comment]
Hi @bfirsh I'd like to tackle this as my first contribution. Is that okay?

**Comment by enochkan** [comment]
@bfirsh created a PR for fix: https://github.com/replicate/keepsake/pull/543

**Comment by enochkan** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/21212915/110221740-f0e30900-7ec5-11eb-8803-7f7a64651bb6.png">

Works on collar
