### ISSUE TITLE
Testing error in PL Callback

### ISSUE THREAD

**Issue by enochkan** [replicate/keepsake#547]
Please refer to the issue [here](https://github.com/replicate/keepsake/pull/543#pullrequestreview-605795161)

Testing PL Callback results in HTTP error 403 (similar to this [issue](https://github.com/pytorch/vision/issues/1938#issuecomment-594768546)). There are simple workarounds in `test_pl_callback` using `urllib` such as:
```python
def set_header_for(self):
         opener = urllib.request.build_opener()
         opener.addheaders = [("User-agent", "Mozilla/5.0")]
         urllib.request.install_opener(opener)

     def prepare_data(self):
         self.set_header_for()
         # download only
         MNIST(
             "/tmp/keepsake-test-mnist",
```
However it breaks the overall build, hence further investigation is needed.

**Comment by bfirsh** [comment]
Thanks! This is the real fix: #551
